### ISSUE TITLE
关于2.0重构规划及建议征集

### ISSUE THREAD

**Issue by eyson** [eyson/wechat-solita#2]
暂定 5 月份前完成 2.0 版本重构，其中包括 `UI` / `代码` 等将进行全新构建。

目前存在的问题：

- UI 粗糙
- 交互体验差
- 代码逻辑混乱
- 性能差

**2.0 版本你有什么好的建议都欢迎讨论。**

**Comment by exelin** [comment]
商品接龙的话  可以给出多个sku的选项，同时增加团长汇总功能    一下子能看到多sku各订了几个  方便进货

**Comment by eyson** [comment]
> 商品接龙的话 可以给出多个sku的选项，同时增加团长汇总功能 一下子能看到多sku各订了几个 方便进货

汇总统计功能可以考虑下，但多SKU暂时先不规划了。毕竟这不是商详页~不要做得那么复杂
